### ISSUE TITLE
Aime not working properly

### ISSUE THREAD

**Issue by RubberDuckShobe** [evan-choi/MiniMe#1]
Hello, I'm having issues with Aime on CHUNITHM Paradise Lost.
I can create my profile and play with it once, but it won't work anymore in later sessions.
If I try to scan the card, it takes a long time attempting to connect, but it eventually fails, saying it can't connect and forces me to play as a guest. When I delete the databases that MiniMe creates, it'll work for one session with a new card again.
Below is the console log when this happens:

```
[Aime 20:45:55 INF] e429efec-b722-4781-9e65-0ffb9e45a806 Session opened.
[Aime 20:45:55 INF] e429efec-b722-4781-9e65-0ffb9e45a806 Request {"Field20": 727088352, "Field24": 1, "Field28": 727088352, "Field2C": 0, "Field30": 0, "Field34": 0, "Field38": 0, "Field3C": 0, "GameId": "SDBT", "KeyChipId": "A69E01A8888", "$type": "LogRequest"} received.
[Aime 20:45:55 INF] e429efec-b722-4781-9e65-0ffb9e45a806 Response {"Status": 1, "$type": "LogResponse"} in 3.3558ms
[Aime 20:45:55 INF] e429efec-b722-4781-9e65-0ffb9e45a806 Request {"GameId": null, "KeyChipId": null, "$type": "GoodbyeRequest"} received.
[Aime 20:45:55 INF] e429efec-b722-4781-9e65-0ffb9e45a806 Response null in 1.5205ms
[Aime 20:45:55 INF] e429efec-b722-4781-9e65-0ffb9e45a806 Session closed.
[Chunithm 20:45:56 INF] Request starting HTTP/1.1 POST http://127.0.0.1:9001/ChuniServlet/GameLoginApi application/json 83
[Chunithm 20:45:56 INF] Request finished in 35.9279ms 200 application/json; charset=utf-8
[Chunithm 20:45:56 INF] Request starting HTTP/1.1 POST http://127.0.0.1:9001/ChuniServlet/GetUserDataApi application/json 31
[Chunithm 20:47:00 INF] Request starting HTTP/1.1 POST http://127.0.0.1:9001/ChuniServlet/GameLogoutApi application/json 31
[Chunithm 20:47:00 INF] Request finished in 28.4633ms 200 application/json; charset=utf-8
[Chunithm 20:49:24 ERR] Connection id "0HMEBKKRQ99PH", Request id "0HMEBKKRQ99PH:00000003": An unhandled exception was thrown by the application.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 13: 'database or disk is full'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at MiniMe.Chunithm.Data.ChunithmContext.FindProfileWithQuery(Nullable`1 aimeId, Func`2 wrapper)
   at MiniMe.Chunithm.Data.ChunithmContext.FindProfileWithAllData(Nullable`1 aimeId)
   at MiniMe.Chunithm.Controllers.ServletController.GetUserData(GetUserDataRequest request)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at MiniMe.Core.AspNetCore.Middleswares.MiddlewareBase.Next(HttpContext context)
   at MiniMe.Core.AspNetCore.Middleswares.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at MiniMe.Core.AspNetCore.RequestDecompression.RequestDecompressionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at MiniMe.Core.AspNetCore.RequestDecompression.RequestDecompressionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MiniMe.Core.AspNetCore.Middleswares.MiddlewareBase.Next(HttpContext context)
   at MiniMe.Core.AspNetCore.Middleswares.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[Chunithm 20:49:26 INF] Request finished in 210077.7344ms 0
```

**Comment by evan-choi** [comment]
`SQLite Error 13: 'database or disk is full'.`

Disk is free?

**Comment by RubberDuckShobe** [comment]
Yes, C:\ has about 20GB of space and D:\ (with the database) has 60GB left

**Comment by jtwine** [comment]
Just mentioning it as an aside - a corrupt database file might cause that error as well as no space in whatever temp location SQLite (read: the hosting app/service) is using.  For example, if you have **%TEMP%** on a different partition and THAT is running out of space, or if quotas are in effect and you are exceeding your FS quota.

You can also use the `.dump` command to dump a database, even if it is corrupted.  You can then backup your existing DB file and use that output and feed it back into SQLite and create a new, working version of the database and see if that works for you.

See [here (`.dump` command)](https://www.sqlitetutorial.net/sqlite-dump/) and [here (stackoverflow)](https://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed/5275022) for more information.

**Comment by RubberDuckShobe** [comment]
The SQLite3 CLI's integrity check returns ``ok`` for both ``aime.db`` and ``chunithm.db``, so the database doesn't seem to be corrupt
